name: Publish release
on:
  release:
    types: [created]
jobs:
  test-js:
    name: 'JS v0.2.2' # v0.2.2 == commit below
    uses: paulmillr/jsbt/.github/workflows/release.yml@8db14713888c4c7dc1b031d480213cd67f5c422d
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      contents: write
      id-token: write
