name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'JS v0.2.2' # v0.2.2 == commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@698d27bde26a862e1e0d21354ee0d72174539181
    with:
      clone-submodules: true
